### ISSUE TITLE
Use "Final return"

### ISSUE THREAD

**Issue by theRemix** [GaganTut/js-functions-1#2]
It is _slightly_ better code practice to use a *final return*.

example from https://github.com/GaganTut/js-functions-1/blob/master/functions.js#L97
```javascript
function calculate(operation, x, y) {
  var result;
  var output;
  if (operation === "add") {
    result = add(x, y);
    output = x + " + " + y + " = " + result;
  } else if (operation === "subtract") {
    // ...
  } else if (operation === "multiply") {
    // ...
  } else if (operation === "divide") {
    // ...
  }

  console.log(output);
  return result;
}
```

`letterGrade` should also be refactored in this way
https://github.com/GaganTut/js-functions-1/blob/master/functions.js#L218

`incrementReviews` should also be refactored in this way
https://github.com/GaganTut/js-functions-1/blob/master/functions.js#L241

**Comment by GaganTut** [comment]
Fixed Them
